on: [push,pull_request]

jobs:
  job1:
    name: Sphinx Pages
    runs-on: ubuntu-latest
    steps:
      - uses: sky-dream/sphinx-pages@master
        id: sphinx-pages
        with:
          github_token: ${{ secrets.SPHINX_PAGES_SECRET }}
          create_readme: true

